version: 2.1

orbs:
  maven: circleci/maven@0.0.12
build:
    working_directory: ~/project
requires:	
- image: selenium/standalone-chrome:3.1.0  
workflows:

  maven_test:
    jobs:
      - build
      - maven/test # checkout, build, test, and upload test results
