version: 2.1
orbs:
  maven: circleci/maven@0.0.12

jobs:
  provision_chromedriver:
    working_directory: ~/project
    docker:
      - image: selenium/standalone-chrome:3.1.0 
    steps:
      - run: echo "Selenium chromedriver installed"
      - run: 
          name: Start Selenium
          command: /opt/bin/entry_point.sh
          background: true
# executors:
#   selenium_chrome:
#     working_directory: ~/project
#     docker:
#       - image: selenium/standalone-chrome:3.1.0 

# requires:
#   - test_windows
#   - image: selenium/standalone-chrome:3.1.0  

workflows:
  maven_test:
    jobs:
      - provision_chromedriver
      - maven/test: # checkout, build, test, and upload test results
          requires:
            - provision_chromedriver
    
