version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
  
workflows:
  maven_test:
    jobs:
    test:
    docker:
      - image: 'cimg/node:13.12'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - maven/test # checkout, build, test, and upload test results
