version: 2.1
orbs:
  maven: circleci/maven@0.0.12

executors:
  selenium_maven:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: selenium/standalone-chrome:3.1.0 

jobs:
  test:
    executor: selenium_maven
    steps:
      - attach_workspace:
          at: ~/project
      - run: mvn **/*Test*.java

  # provision_chromedriver:
  #   working_directory: ~/project
  #   docker:
  #     - image: selenium/standalone-chrome:3.1.0 
  #   steps:
  #     - run: echo "Selenium chromedriver installed"
  #     - run: 
  #         name: Start Selenium
  #         command: /opt/bin/entry_point.sh
  #         background: true

# requires:
#   - test_windows
#   - image: selenium/standalone-chrome:3.1.0  

workflows:
  maven_test:
    jobs:
      - test
      # - provision_chromedriver
      # - maven/test: # checkout, build, test, and upload test results
      #     requires:
      #       - provision_chromedriver
    
