jobs:
  test:
    docker:
      - image: 'cimg/node:13.12'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
orbs:
  browser-tools: circleci/browser-tools@x.y
version: 2.1
orbs:
  maven: circleci/maven@0.0.12
requires:
- test_windows
- image: selenium/standalone-chrome:3.1.0  
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
    
