version: 2.1
orbs:
  maven: circleci/maven@0.0.12

jobs:
  provision_chromedriver:
    docker:
      - image: selenium/standalone-chrome:3.1.0 
    steps:
      - run: echo "selenium chromedriver installed"

# requires:
#   - test_windows
#   - image: selenium/standalone-chrome:3.1.0  

workflows:
  maven_test:
    jobs:
      - provision_chromedriver
      - maven/test: # checkout, build, test, and upload test results
          requires:
            - provision_chromedriver
    
