version: 2.1
orbs:
  maven: circleci/maven@0.0.12
  
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: 'cimg/node:13.12'
      - image: selenium/standalone-chrome:3.1.0 
    steps:
      
      - run: echo "Selenium chromedriver installed"
      - attach_workspace:
          at: ~/project
      - persist_to_workspace:
          root: /usr/bin
          paths:
            - chromedriver
      

workflows:
  maven_test:
    jobs:
      - build
      - maven/test: # checkout, build, test, and upload test results
          test_results_path: test-reports
          requires:
            - build
      
