version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  
workflows:
type: shell
command: |
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
