version: 2.1
orbs:
  win: circleci/windows@2.3.0
  maven: circleci/maven@0.0.12
jobs:
  build:
    executor: win/default
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
