version: 2.1
orbs:
  maven: circleci/maven@0.0.12
requires:
- test_windows
- image: selenium/standalone-chrome:3.1.0  
workflows:
    jobs:
    build:
    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          PGHOST: 127.0.0.1
          CI: true
          CIRCLECI: true
          RAILS_ENV: test
          CI_REPORTS: ${CIRCLE_TEST_REPORTS}/rspec
          WAIT_TIME: 3
          PGUSER: root
      - image: redis:3.2.5
      - image: circleci/postgres:9.5.6-alpine
      - image: selenium/standalone-chrome:3.5.1
      - image: selenium/standalone-firefox:latest
      - image: circleci/node:6-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
    
