version: 2.1
orbs:
  maven: circleci/maven@0.0.12

executors:
  selenium_maven:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: selenium/standalone-chrome:3.1.0 

jobs:
  build:
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
  # test:
  #   executor: selenium_maven
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: mvn **/*Test*.java

  # provision_chromedriver:
  #   working_directory: ~/project
  #   docker:
  #     - image: selenium/standalone-chrome:3.1.0 
  #   steps:
  #     - run: echo "Selenium chromedriver installed"
  #     - run: 
  #         name: Start Selenium
  #         command: /opt/bin/entry_point.sh
  #         background: true

# requires:
#   - test_windows
#   - image: selenium/standalone-chrome:3.1.0  

workflows:
  maven_test:
    jobs:
      # - test
      - build
      - maven/test: # checkout, build, test, and upload test results
          requires:
            - build
    
