version: 2.1
orbs:
  maven: circleci/maven@0.0.12

# executors:
#   java:
#     working_directory: ~/project
#     docker:
#       - image: circleci/openjdk:8-jdk-stretch
#       - image: selenium/standalone-chrome:3.1.0 

jobs:
  # build:
  #   docker:
  #     - image: circleci/node:jessie-browsers
  #   steps:
  #     - checkout
  #     - run: mkdir test-reports
  #     - run:
  #         name: Download Selenium
  #         command: sudo apt-get install chromium-chromedriver
  #     - run: ls /usr/bin
      # - run:
      #     name: Start Selenium
      #     command: java -log test-reports/selenium.log
      #     background: true
  # test:
  #   executor: selenium_maven
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - run: mvn **/*Test*.java

  build:
    working_directory: ~/project
    docker:
      - image: selenium/standalone-chrome:3.1.0 
    steps:
      - run: echo "Selenium chromedriver installed"
      - attach_workspace:
          at: ~/project
      - persist_to_workspace:
          root: /usr/bin
          paths:
            - chromedriver
      # - run: 
      #     name: Start Selenium
      #     command: /opt/bin/entry_point.sh
      #     background: true

# requires:
#   - test_windows
#   - image: selenium/standalone-chrome:3.1.0  

workflows:
  maven_test:
    jobs:
      # - test
      - build
      - maven/test: # checkout, build, test, and upload test results
          # steps:
          #   - attach_workspace:
          #     at: ~/project
          test_results_path: test-reports
          requires:
            - build
    
